### ISSUE TITLE
Error deploying based on Lambda size limits

### ISSUE THREAD

**Issue by provderek** [ivarvermeulen/nuxt-serverless-at-edge#17]
Hey Ivar, thanks for the demo...trying to get our Nuxt project running serverless, and based on your demo, tried to get running in lambda. If I just build a complete skeleton project with nuxt create app, and only add in serverless follwoing your steps, my deploy errors out saying I already hit the 50MB Lambda function limit. Serverless uses aws api which is like 60MB or something alone. In a real production project with many libraries in node modules, how can we possibly run serverless in lambda with their limits? What am I missing? Thanks

**Comment by ivarvermeulen** [comment]
Hi @provderek, aws-sdk is available in the Lambda runtime so there is no need to add it to your node modules. When you need aws-sdk for local development add it to your dev dependencies and use this option within serverless https://github.com/ivarvermeulen/nuxt-serverless-at-edge/blob/master/serverless.yml#L46 to make sure the dev dependencies aren't added to the deploy package

**Comment by provderek** [comment]
ahh, okay, really appreciate your time and help Ivar. Thanks.
